### PR TITLE
?: is suggested for ifs with nested if/elses but should not be

### PR DESCRIPTION
**Pull request by danbrad**
ConvertIfStatementToConditionalTernaryExpressionCodeRefactoringProvider has a comment:

  //make sure to check for multiple statements

but multiple descendent expressions are also problematic. The effect of this is that ?: is suggested, but only the first of the descendent expressions is pulled through, causing a lot of code ot be potentially removed. It makes no sense to convert an if with nested if/else to be converted to ?:

### CODE REVIEW

**Comment by Rpinski** [comment]
Thank you for your pull request! The fix may be built event simpler: What about using ``ChildNodes()`` instead of ``DescendantNodesAndSelf()``? It doesn't make sense to peek expression statements, which are not direct children of the outer if.

**Comment by danbrad** [comment]
Thanks for the feedback - I'm starting to get my head around this now.

How about this latest version? Feels much better (and clearer) to me..

**Comment by Rpinski** [comment]
Looks good now, thank you!

**Comment by danbrad** [comment]
Cool, thanks - happy to help with any other bugs if there are repros.

**Pull request merged**
