### PR TITLE
Porting RedundantExplicitSizeArray

### PR DESCRIPTION
**Pull request by Kavignon**
I'm look for the way to get the int value inside the brackets. I dont know what it is. I tested it with an array creation expression and thought  either Rank or Sizes.Count could help but they didnt.
As for the code fix provider, I think it'll be simple, recreate a new node without specifying the int value.

### CODE REVIEW

**Comment by Kavignon** [comment]
I should also make a check if the int value is either 0 or if the number of expressions inside {} is not existing ? 
Which would be better or should I do both ?

**Comment by mkrueger** [comment]
The code fix provider is fairly trivial - a RemoveNode of arrayType.RankSpecifiers[0] should do it.

Please try to learn & understand how the code fix providers work.

**Comment by Kavignon** [comment]
@mkrueger  look new commit

**Comment by Kavignon** [comment]
Is this better now ?

**Comment by Kavignon** [comment]
@mkrueger I'm lost,  you said ChildNodes were not the way to go. So I modified my code.
IF I have more than one RankSpecifier, I should return false ?
When you said it was good before, exaclty what was good and what was wrong ? What's wrong with the analyzer currently ?

**Comment by mkrueger** [comment]
Something like that would do it:

var rs = arrayType.RankSpecifiers;
if (rs.Length != 1 || rs[0].Sizes.Length != 1)
    return false;

**Comment by Kavignon** [comment]
if that check useless ? : if (node.Initializer.Expressions.Count == (int)intSizeValue.Value)
All right, I'l add this to the analyzer.
As for the code fix provider, like we said, it's straightforward. Is everything in order in that department?

**Comment by mkrueger** [comment]
It looks good - I'll need to check/test that. I have only looked briefly over that and it's ok I think. 
I still need to sort some things out. But I think I'll have time at friday for a closer look.

**Comment by Kavignon** [comment]
@mkrueger ?

**Comment by Kavignon** [comment]
@mkrueger

**Comment by mkrueger** [comment]
merged - thanks.

There is just one little bug. You assume that:

(int)intSizeValue.Value


is valid. But if someone writes new int[3.0]; it'll surely crash. It's true that this is invalid c# - but users may write invalid c# :)

**Comment by Rpinski** [comment]
It has also crashed when applied on ``var arr = new int[3];``, because then ``node.Initializer`` is ``null``. Fixed it in a28d22916d051086159cbba143c807c7118c8adc.

**Pull request merged**
