### PR TITLE
Ported RedundantExplicitNullableCreation

### PR DESCRIPTION
**Pull request by Kavignon**
Code provider
Analyzer -> Wrote comment for some check I'm doing from previous analyzer. I'd like to make sure it's needed.

### CODE REVIEW

**Comment by Kavignon** [comment]
I removed ChildNodes() usage

**Comment by Kavignon** [comment]
@mkrueger

**Comment by mkrueger** [comment]
Tests are failing for me.

btw. is there any pull request which tests run ? Just go to http://www.nunit.org/ download it and run the NUnit gui runner if you can't run tests inside the IDE.

**Comment by Kavignon** [comment]
Hi @mkrueger 
Tests are failing for me too. 
For some reason, I dont understand what is so wrong with the code fix provider because in my tests, my analyzer does the it, the tryget returns the true value whenever it's needed.
But I can't debug the code fix.

I'll try that tool today. Maybe I'll have a better chance of understanding whats so profoundly wrong with the code. I will keep you updated and fix every test that needs fixing ASAP.

Thank you

**Comment by mkrueger** [comment]
I'm not really sure what you wanted to do - but it seems that you didn't really understand what the action is about. The code fix provider was wrong - you replaced the node with a new object creation - that doesn't make sense. The unit tests show what the action does (removing a redundant nullable object creation).

The tests need to be ported - the regions need to be marked with $ .... $, the disable mechanism has changed a bit from NR5 - needs to be ported as well.

Try to avoid doing string comparisons like :

if (objectCreationSymbol.OriginalDefinition.ToString().Equals("System.Nullable<T>.Nullable(T)"))

- they're pretty unefficient. GetDeclaredSymbol is something that should be called on a declaration. An object creation is an expression - GetSymbolInfo or GetTypeInfo is for that case.

Here would be a possible diff. Try to apply it - or port it manually. Then understand it & add it to your commit. And try to do the same thing to the other analyzers. Only a green test is a valid port.

diff --git a/RefactoringEssentials/CSharp/Diagnostics/Synced/RedundanciesInCode/RedundantExplicitNullableCreationAnalyzer.cs b/RefactoringEssentials/CSharp/Diagnostics/Synced/RedundanciesInCode/RedundantExplicitNullableCreationAnalyzer.cs
index 237df04..d1155b2 100644
--- a/RefactoringEssentials/CSharp/Diagnostics/Synced/RedundanciesInCode/RedundantExplicitNullableCreationAnalyzer.cs
+++ b/RefactoringEssentials/CSharp/Diagnostics/Synced/RedundanciesInCode/RedundantExplicitNullableCreationAnalyzer.cs
@@ -4,6 +4,7 @@
 using System.Linq;
 using Microsoft.CodeAnalysis.CSharp;
 using Microsoft.CodeAnalysis.CSharp.Syntax;
+using System.Diagnostics;
 
 namespace RefactoringEssentials.CSharp.Diagnostics
 {
@@ -48,18 +49,18 @@ static bool TryGetDiagnostic(SyntaxNodeAnalysisContext nodeContext, out Diagnost
             if (objectCreation == null)
                 return false;
 
-            var objectCreationSymbol = nodeContext.SemanticModel.GetDeclaredSymbol(objectCreation);
-            if (objectCreationSymbol == null)
+            var objectCreationSymbol = nodeContext.SemanticModel.GetTypeInfo(objectCreation);
+            if (objectCreationSymbol.Type == null)
                 return false;
-
+            
             int? i = new int?(5);
 
             //Not so sure about this check but was there before
-            var parentVarDeclaration = objectCreation.Parent.Parent as VariableDeclarationSyntax;
+            var parentVarDeclaration = objectCreation?.Parent?.Parent?.Parent as VariableDeclarationSyntax;
             if (parentVarDeclaration != null && parentVarDeclaration.Type.IsVar)
                 return false;
-
-            if (objectCreationSymbol.OriginalDefinition.ToString().Equals("System.Nullable<T>.Nullable(T)"))
+            
+            if (objectCreationSymbol.Type.IsNullable ())
             {
                 diagnostic = Diagnostic.Create(descriptor, objectCreation.GetLocation());
                 return true;
diff --git a/RefactoringEssentials/CSharp/Diagnostics/Synced/RedundanciesInCode/RedundantExplicitNullableCreationCodeFixProvider.cs b/RefactoringEssentials/CSharp/Diagnostics/Synced/RedundanciesInCode/RedundantExplicitNullableCreationCodeFixProvider.cs
index b368d00..1658968 100644
--- a/RefactoringEssentials/CSharp/Diagnostics/Synced/RedundanciesInCode/RedundantExplicitNullableCreationCodeFixProvider.cs
+++ b/RefactoringEssentials/CSharp/Diagnostics/Synced/RedundanciesInCode/RedundantExplicitNullableCreationCodeFixProvider.cs
@@ -40,12 +40,7 @@ public override FixAllProvider GetFixAllProvider()
 
             context.RegisterCodeFix(CodeActionFactory.Create(objectCreation.Span, diagnostic.Severity, "Redundant explicit nullable type creation", token =>
             {
-                var newNode = SyntaxFactory.ObjectCreationExpression(objectCreation.NewKeyword, objectCreation.Type,
-                    argumentList, objectCreation.Initializer);
-
-                var newRoot = root.ReplaceNode(objectCreation,
-                    newNode.WithLeadingTrivia(objectCreation.GetLeadingTrivia())
-                        .WithAdditionalAnnotations(Formatter.Annotation));
+                var newRoot = root.ReplaceNode(objectCreation, argumentList.Arguments[0].Expression.WithAdditionalAnnotations(Formatter.Annotation));
 
                 return Task.FromResult(document.WithSyntaxRoot(newRoot));
             }), diagnostic);
diff --git a/Tests/CSharp/Diagnostics/RedundantExplicitNullableCreationTests.cs b/Tests/CSharp/Diagnostics/RedundantExplicitNullableCreationTests.cs
index b93d8db..454f929 100644
--- a/Tests/CSharp/Diagnostics/RedundantExplicitNullableCreationTests.cs
+++ b/Tests/CSharp/Diagnostics/RedundantExplicitNullableCreationTests.cs
@@ -14,7 +14,7 @@ class FooBar
 {
 	void Test()
 	{
-		int? i = new int?(5);
+		int? i = $new int?(5)$;
 	}
 }
 ", @"
@@ -36,7 +36,7 @@ class FooBar
 {
 	void Test()
 	{
-		int? i = new System.Nullable<int>(5);
+		int? i = $new System.Nullable<int>(5)$;
 	}
 }
 ", @"
@@ -72,7 +72,7 @@ class FooBar
 {
 	void Test()
 	{
-		// ReSharper disable once RedundantExplicitNullableCreation
+#pragma warning disable " + CSharpDiagnosticIDs.RedundantExplicitNullableCreationAnalyzerID + @"
 		int? i = new int?(5);
 	}
 }

**Comment by Kavignon** [comment]
I had forgot about the $$ in the test while porting !
Well this has a major impact on things !!
as for the object creation, it made sense for me looking at how it worked
I'll use the nullable syntax instead
"Here would be a possible diff. Try to apply it - or port it manually." I don''t understand what you mwant by this !

**Comment by mkrueger** [comment]
I mean that you should add that to your branch or do something like that - at least the tests need to be green. And see earlier comments

**Comment by Kavignon** [comment]
I think i may have identified many mistakes in my many PRs.
My goal would be to fix them by this time next week so that we have a grand
total of 16 addition on my end and I can continue to work on the library
better than I've thus far !

Have a nice a evening.

I'll make my best to make sure you don't  regret having me to mentor,
promise !


Kevin

On Friday, July 17, 2015, Mike Krüger <notifications@github.com> wrote:

> I mean that you should add that to your branch or do something like that -
> at least the tests need to be green. And see earlier comments
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/icsharpcode/RefactoringEssentials/pull/14#issuecomment-122388003>
> .
>


-- 
Kevin Avignon
Étudiant en génie des technologies de l'information (ETS)

**Comment by mkrueger** [comment]
Seems to work - thanks.

**Comment by Kavignon** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Kevin

Confirm that you know Kevin: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=KTTVdEmW&invitationId=6208290943456604161&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eivzc8e4j%7Ege








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ivzc8e4j-ge&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEfopqAnH09JAAAAVihIWrNifyHybmvZbr5PFu-fegI4SImJNKFDexegGc8Z_6qQmmySmlpJ2_D87gSe5ubr2o2X0EOxyykxPQI9FCu5q3wmCjHzAuAD6wy380gSiam0c0ldmH5HGyWEGPA2P4gdqSC6ARsP12o6ua2bGptjXJm6AUiLVUh6_P7dz_ePNF7_tx5Mgrx70dlhVpOsg97pY3yDQ&eid=0-ivzc8e4j-ge


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ivzc8e4j-ge&a=customerServiceUrl&ek=invite_guest

© 2016 LinkedIn Corporation, 1000 West Maude Avenue, Sunnyvale, CA 94085. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Kavignon** [comment]
Kevin Avignon would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=KTTVdEmW&invitationId=6208290943456604161&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-%7Etovqyy%7Eiw6msles%7E8j

View Kevin Avignon&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=KTTVdEmW&invitationId=6208290943456604161&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-%7Etovqyy%7Eiw6msles%7E8j





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-tovqyy-iw6msles-8j&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=-tovqyy-iw6msles-8j&loid=AQHufeFQflAG4AAAAVi8Msfe6Qqee3LsYemD0dMCByiN2dPUqaE6ATwWYoDB729ds0c9F-aHUvRI0nLw5CQs8X4vwbPtYYc3vuEtZQlt-fi6Yl1EoizKByx8T6PHf5UQhdD1qu9WSbo0gJHzpYaEVTsuxq2niKK9KkaNJTuDnpMhKojdJw4YuKpsdjoNEioBWeIzuibw8dLRltmLzw291_PPHw6jqg

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-tovqyy-iw6msles-8j&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request merged**
