### PR TITLE
Ported MemberCanBeMadeStatic analyzer

### PR DESCRIPTION
**Pull request by Kavignon**
What should done with the code fix provider as it's not a single situation to fix ? I'm unsure with how to approach the situation...

### CODE REVIEW

**Comment by mkrueger** [comment]
I miss the code fix provider ...

**Comment by Kavignon** [comment]
What's what good for ?
I'm sorry for the event field. I was trying to figure out how to access the accessors and I forgot to remove it from the analyzer.
Do you mean to tell me that this is not okay : "                 methodDeclaration.Modifiers.Any(SyntaxKind.StaticKeyword) " ??

**Comment by Kavignon** [comment]
As of the code fix provider, that's what I was wondering about since I have three types of nodes
1. When doing the code fix provider for method declaration,I should check the names for '$' and remove that char from the string ?

2. How can I add the static keyword to a Node ? I don't find any equivalent for RemoveNode like AddNode?

3.When I have node and I make sure it's Method or Property or Event, I create a specific context for each of them ? S

I remove the dollar sign, I add the static keyword  but I'm not sure about context? After adding the node static keyword,I register the code action without adding anything else to the context ?

**Comment by Kavignon** [comment]
@mkrueger

**Comment by Kavignon** [comment]
methodDeclaration.Modifiers.Add(new SyntaxToken().)
I'm looking for a way to add the StaticKeyword in the modifiers, but Idon't know how!
Help please ? @mkrueger

**Comment by mkrueger** [comment]
Basically:

methodDeclaration.WithModifiers (methodDeclaration.Modifiers.Add (SyntaxFactory.Token (SyntaxKind.StaticKeyword))

**Comment by mkrueger** [comment]
Test fails for me.
Some things:
+ Test analyzer spans need to be checked with $ ... $ 
+ Diagnositc is added to the whole method declaration - report that only to the method identifier

**Comment by Kavignon** [comment]
The project is missing a commit that's local on my machine, I think.
But it's still not working! Could you please check the code in the later commit and in my PR's in which i have been active in the past few days ? Thanks Mike!

**Comment by mkrueger** [comment]
Makes more sene if you push everything you've first.

**Comment by Kavignon** [comment]
everything has been push!

**Comment by mkrueger** [comment]
Issues: 

* Analyzer shouldn't mark the whole method - only the method name. Marking too much looks awkward in the editor. (mentioned earlier)
* Formatting in the analyzer file is screwed up in the Initialize method
* The code fix provider replace nodes are missing a .WithAdditionalAnnotations(Formatter.Annotation) 
* The fix providers are often named 'Redundant explicit nullable type creation' that makes no sense
* In TestPrivateMethod the Analyze parameters ,1,1 can be removed - they're a left over from NR5. Roslyn doesn't support sub issues.
* I don't understand the '// I don't know what to put there... ' comments because all you need to put there is there - at least it looks like so

Note:
btw. there are helper methods which may be usefull - search for AddModifier or AddNewModifier. They're private but can be made internal.

**Comment by Kavignon** [comment]
Look at commit message, but this could be ported @mkrueger

**Comment by mkrueger** [comment]
btw. red tests usually mean something doesn't work.

**Comment by mkrueger** [comment]
btw. your actions reformat the whole file. Be careful what you annotate with format.

**Comment by mkrueger** [comment]
I merged it and tried to fix it - but there is basically no check if a member could be made static.

This needs to analyze if non static members are accessed in the bodies - and as far as I can tell this does not.

**Pull request merged**
