### PR TITLE
Porting LocalVariableNotUsed analyzer in progress

### PR DESCRIPTION
**Pull request by Kavignon**
Some issues with AnalyzeDataFlow breaking the debug : ": System.ArgumentOutRangeException Index was out of range Must be non negative and lesser than the size of the collection"
But I do think that it should not take long to fix.

### CODE REVIEW

**Comment by Kavignon** [comment]
I put this in comment but you did not give me any feed back about this :
            //// check if variable is assigned
            //if (!variableInitializer.ChildNodes().OfType<EqualsValueClauseSyntax>().Any()) //I thought that we should only look for var... If looking for any variables, this check from the ancient visitor should not be here.
            //    return false;

**Comment by Kavignon** [comment]
I made some research and ask around the web too, it does not seem that it's possible only from properties. Could you shine some light on what you meant earlier ?

**Comment by Kavignon** [comment]
@mkrueger

**Comment by mkrueger** [comment]
There are properties for almost everything you tend to use child nodes - I already said that dozen of times.

So for the last time:

Avoid :
var variableInitializer = localDeclaration?.DescendantNodes().OfType<VariableDeclaratorSyntax>()
var decl = variableInitializer.Parent as VariableDeclarationSyntax;

It's equivalent to:
var decl = localDeclaration.Declaration;

**Comment by Kavignon** [comment]
I'll fix it, Somehow. I will make the priority of today and get it done
somehow

On Monday, August 10, 2015, Mike Krüger <notifications@github.com> wrote:

> There are properties for almost everything you tend to use child nodes - I
> already said that dozen of times.
>
> So for the last time:
>
> Avoid :
> var variableInitializer = localDeclaration?.DescendantNodes().OfType()
> var decl = variableInitializer.Parent as VariableDeclarationSyntax;
>
> It's equivalent to:
> var decl = localDeclaration.Declaration;
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/icsharpcode/RefactoringEssentials/pull/11#issuecomment-129389953>
> .
>


-- 
Kevin Avignon
Étudiant en génie des technologies de l'information (ETS)

**Comment by Kavignon** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Kevin

Confirm that you know Kevin: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=LcqJ6EfD&invitationId=6208290924385095680&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eivzc5fk8%7E4c








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ivzc5fk8-4c&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEfrfpos40tfgAAAVihH1c253a-VlKbAhJfTLKvNe24whLFc2Z0qIJUONcEQaMirjwL-ilOcOAapyuGXzA9YAgWk9B--BSsjPKNhpG9OmItjJ_qZ3mVE-fvNThSyUU4iS0BTCObNx1Io_TJrfiEPS32CmxBN4_SaoLtWBQ9wpCzazG6uPwDzRG2tEXCYtexZ3gtieZtaMXyXbD1hNPeOCqY4g&eid=0-ivzc5fk8-4c


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ivzc5fk8-4c&a=customerServiceUrl&ek=invite_guest

© 2016 LinkedIn Corporation, 1000 West Maude Avenue, Sunnyvale, CA 94085. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Kavignon** [comment]
Kevin Avignon would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=LcqJ6EfD&invitationId=6208290924385095680&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-w0by43%7Eiw6ms8xd%7Emz

View Kevin Avignon&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=LcqJ6EfD&invitationId=6208290924385095680&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-w0by43%7Eiw6ms8xd%7Emz





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=w0by43-iw6ms8xd-mz&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=w0by43-iw6ms8xd-mz&loid=AQGPD_QCiUbcEgAAAVi8PhzmbGn0GvHGtepDgukD-ahsAzODEMrFrrfOwxJUxS6PqEoyHNW78XHK-Eoffxex7MCPvuCWXapT4A9O_2zJ_2QNYIDmKk6DofdXAa-rn4bnXXd4LxaUtW3o2NLt7p7fR9IABbV9fRdl-vYzeQ8yjgD3djglMFG7E-XA_EfGZhTznu1u-EHOfdHY2rMdg8mSF2sRdTrIsQ

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=w0by43-iw6ms8xd-mz&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request closed without merging**
