### PR TITLE
Use Method Any instead of Count 

### PR DESCRIPTION
**Pull request by Kavignon**
Created analyzer for the LINQ any method.
Code fix provider looks a bit more work than I thought. I will make a future commit for that elementé

### CODE REVIEW

**Comment by Kavignon** [comment]
Also going to work on the code fix provider of this today

**Comment by mkrueger** [comment]
Any updates on this branch ?

**Comment by Kavignon** [comment]
Working on this today !

On Friday, August 21, 2015, Mike Krüger <notifications@github.com> wrote:

> Any updates on this branch ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/icsharpcode/RefactoringEssentials/pull/6#issuecomment-133373292>
> .
>


-- 
Kevin Avignon
Étudiant en génie des technologies de l'information (ETS)

**Comment by Kavignon** [comment]
this could almost be merged... Some issue is unables me to finish this ..

**Comment by Kavignon** [comment]
@mkrueger

**Comment by mkrueger** [comment]
I don't think that it can almost be merged.

May even make more sense to redo that. It looks like you're trying to replace any .Count() with .Any(). I do not see how that could work. 

The original idea was to replace things like args.Count() == 0 with args.Any() because that's faster. For that you have to analyze binary expressions - not member access expressions.

**Comment by mkrueger** [comment]
In that state it's not useable - if you want to redo that make a new pr.

**Comment by Kavignon** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Kevin

Confirm that you know Kevin: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=SROQxUHq&invitationId=6208290943922159617&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eivzc61vc%7Eg3








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ivzc61vc-g3&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHf5zfQzAnHeAAAAVihH8qJsUcJHPqoUYwOQcrX-n0FQCYOb7MKRpePDI29ChnDXPWpsva0vZWk9tqY8ct_Rl5K-5IbYikPq3K73rfZP-w7DNNJ6voedxveyF0DOSYNhwasYyqX3Km4lCVN-qDLbK0p20mwJIcACvvo3PF4RRyuYPoML_0LkC1U9rfc3ruHiGard4loIge6k2zaaGD46SBZlg&eid=0-ivzc61vc-g3


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ivzc61vc-g3&a=customerServiceUrl&ek=invite_guest

© 2016 LinkedIn Corporation, 1000 West Maude Avenue, Sunnyvale, CA 94085. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Kavignon** [comment]
Kevin Avignon would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=SROQxUHq&invitationId=6208290943922159617&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-%7E5kzrum%7Eiw6msldt%7Em8

View Kevin Avignon&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=SROQxUHq&invitationId=6208290943922159617&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-%7E5kzrum%7Eiw6msldt%7Em8





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-5kzrum-iw6msldt-m8&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=-5kzrum-iw6msldt-m8&loid=AQEm2eIA_Py-egAAAVi8OS7gCuK6JUdIsKOhop-SRlh9u2DiBvkZdDVeDHU-1XSkh4oO6_7oAm4vJTCBOZYFGb5_zX-E0zwP4r5bATylgnM5NIX5pcwtSJ1O7emBBe28YLjUBfQAhbcxfQuIQaB5r1MJ6zkr1c-CXZm3WiBG_cNwT6EsloGXCNxbamDHBOAt6u0d3j9_PyfPpgR_WisyYJpu7qSpEQ

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-5kzrum-iw6msldt-m8&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request closed without merging**
