### PR TITLE
Better checking if type symbol implements special type interface

### PR DESCRIPTION
**Pull request by Novakov**
When I was working on PutInsideUsing and IterateViaForeach refactorings I noticed that checking if type symbol is `IDisposable` or `IEnumerable` is tricky. 

This pull request adds mechanism to check if type symbol implements specific special type interface and updates both refactorings to use it.

### CODE REVIEW

**Comment by Novakov** [comment]
Indeed, I had `core.autocrlf` set to `false`. 
Changed & rebased, so now there are no EOL changes.

**Comment by Rpinski** [comment]
Thank you! And sorry, I'll be able to check this only after my vacation.

**Comment by Novakov** [comment]
No problem. Have a good time :)

**Comment by Rpinski** [comment]
Thanks!

**Pull request merged**
