### PR TITLE
Ported RedundantParams

### PR DESCRIPTION
**Pull request by Kavignon**
I left a comment concerning ComposedType as I"m not sure what it is ?
As for the the code fix provider, I'm sure it's trivial but I would like a word with you.
Looking at what the analyzer is doing and the use cases, I just have to add the keyword params at the last parameter in the parameter list ?
It's a bit confusing.

### CODE REVIEW

**Comment by Kavignon** [comment]
@mkrueger

**Comment by mkrueger** [comment]
Tests are failing for me btw.

**Comment by Kavignon** [comment]
@mkrueger what's wrong with Solution #1 ?

**Comment by mkrueger** [comment]
Atm I see 2 issues:

just params should be marked - not the whole parameter:

diagnostic = Diagnostic.Create(descriptor, paramsModifierToken.Value.GetLocation());

btw. why you c heck the paramskeyword twice - if paramsModifierToken.HasValue == true the value is always a params keyword.

The code fix provider is wrong.

I'm not sure what you want to do with:

node.Modifiers.Remove(SyntaxFactory.Token(SyntaxKind.ParamsKeyword))

Do you really think that a new token is part of the modifiers ? 

Something like that may work:

node.Modifiers.Remove(node.Modifiers.First(t => t.SpanStart == context.Span.Start))

**Comment by Kavignon** [comment]
This can be merge now :D @mkrueger

**Pull request merged**
