### PR TITLE
Local variable not used

### PR DESCRIPTION
**Pull request by Kavignon**
Analyzer Done
Code Fix Provider in progress
 (2 test out of 5 passing)

### CODE REVIEW

**Comment by Kavignon** [comment]
Was thinking of using the same snippet of code to determine whenever a variable is not used.
From that, I get a collections a ISymbols of unusued variables. 
Then, I would have resolved every variable declarator and get their ISymbol and verify is unusuedVariable.Contains().. and call remove node on each on them.
I don't have SyntaxNodeAnalysisContext with CodeFixProvider
@mkrueger  How can I do this? It should'nt take long and this can be merged too !

**Comment by mkrueger** [comment]
Basically the code fix provider should not do any analyzation because analyzation is very time consuming and they're running on the UI thread.

Therefore you've to give everything to the code fix provider  - a diagnostic can give a properties dictionary<string, string> to the diagnostic. On the code fix provider side it's accessible via diagnostic.Properties.

**Comment by Rpinski** [comment]
Some additional notes:

* An exception is thrown as soon as code contains methods without body.
* I've disabled ``TestUnusedVariable2`` for now, since support for multi-variable declarations seems not to be implemented yet and that test makes the build "red".

**Comment by Rpinski** [comment]
I've fixed the 2 mentioned issues (d941e4e2da73000540910e57250f4dec02c88225), the exception was quite annoying when thrown all the time while debugging with my test project.

**Pull request merged**
