### PR TITLE
Ported RedundantBaseContructorCall

### PR DESCRIPTION
**Pull request by Kavignon**
Green tests
Logic seems a tiny bit better with the argumentList and arguments check

### CODE REVIEW

**Comment by Kavignon** [comment]
@mkrueger

**Comment by Kavignon** [comment]
can be merge @mkrueger

**Comment by Rpinski** [comment]
This analyzer grays out the whole constructor althrough removing the ``base()`` part only.

**Comment by Rpinski** [comment]
Another issue: If the opening brace is on separate line, this code fix destroys formatting.

**Pull request merged**
