### PR TITLE
Redundant base constructor call

### PR DESCRIPTION
**Pull request by Kavignon**
started porting
need some examples please !

### CODE REVIEW

**Comment by Kavignon** [comment]
i dont know what happened there..
There should only be a single commit

**Comment by mkrueger** [comment]
You're mixing 2 analyzers. In that pull request.

**Comment by mkrueger** [comment]
btw. if you need an example look at RedundantBaseConstructorTests.cs

**Comment by Kavignon** [comment]
I'm going to destroy this branch
Recreate two new branches for each pair of fixes
The PR's should be made by tomorrow, as soon as the tests are green @mkrueger

**Pull request closed without merging**
