### PR TITLE
Fully ported Rewrite if return to rewrite

### PR DESCRIPTION
**Pull request by Kavignon**
Added test cases
Cannot test the ouput test case...

### CODE REVIEW

**Comment by Rpinski** [comment]
Hi Kevin,

just a few hints:

1. You haven't submitted the changed .csproj file, where the ...Tests class was added
1. In ``TryGetDiagnostic()`` the out parameter ``diagnostic`` is never set to anything but ``null``.
1. Some tests contain syntax errors (missing semicolon at return statement). You should also pay attention to formatting of input and output code in tests, because those must match exactly (with all whitespaces, indentation etc.) to the code produced by fix provider.

**Comment by Rpinski** [comment]
Sorry, by "*Some tests contain syntax errors*" I've meant the strings with the input/output code to compare.

**Comment by Kavignon** [comment]
I haven't submitted it because I added the NUnitAdapter to the Test project and it has altered the csproj file too.
I'll add it soon.
As for the TryDiagnostics, I'll have to test it again because the input part was good on my end, maybe I missed something ? 
How can I debug the output part, to verify my code fix provider ? 

I had no idea, I will correct those mistakes and make a new commit !

**Comment by mkrueger** [comment]
Tests are failing for me:
***** RefactoringEssentials.Tests.CSharp.Diagnostics.RewriteIfReturnToReturnTests.When_Return_In_IfStatement
RECS0160/Convert to 'return' statement/[61..101)
***** RefactoringEssentials.Tests.CSharp.Diagnostics.RewriteIfReturnToReturnTests.When_Return_Statement_Corrected
RECS0160/Convert to 'return' statement/[65..107)

**Comment by Kavignon** [comment]
@mkrueger

**Comment by Kavignon** [comment]
Even now, I really can't seem to able to remove the not needed return statement after making the ReplaceNode call.

**Comment by Kavignon** [comment]
I really don't know what else to do... @mkrueger

**Comment by Kavignon** [comment]
can be merged !

**Comment by Kavignon** [comment]
Just saw that the commit modified 2 additionnal files...
Going to move over the files to my master branch and then make a PR ? Or is it ok to leave this like this ?

**Comment by Kavignon** [comment]
@Rpinski  @mkrueger

**Comment by mkrueger** [comment]
I think that can be closed.

Merged https://github.com/icsharpcode/RefactoringEssentials/pull/85

**Pull request closed without merging**
