### PR TITLE
Added refactoring for move class to file in VB

### PR DESCRIPTION
**Pull request by petterek**
Added refactoring for Moving Class Into File. 

No UnitTests is made( do not know howto make them) :)

### CODE REVIEW

**Comment by Rpinski** [comment]
I think it would make sense to suppress this refactoring if the class is the only one in current file already.

**Comment by petterek** [comment]
I will have a look at that. Thank you for your comments

**Comment by paul1956** [comment]
Any idea how to see if the file already exists, I need this code elsewhere also.

**Comment by petterek** [comment]
No not really. I googled this issue a bit and it seems accessing files in a PCL(portable class library) is not that easy.. I do not know why the refactoring is made as a PCL but there is probably a thought behind it. Reusing it on mono probably one of them.

**Comment by siegfriedpammer** [comment]
I am closing this, because 1) VS 2017 already provides this refactoring out-of-the-box and 2) it would require some more fixes, and is copied from another project (except for the conversion).

**Pull request closed without merging**
