### PR TITLE
Ported RedundantIfElseBlock

### PR DESCRIPTION
**Pull request by Kavignon**
Test that I modified from Test to Analyze tells me that expected 0 but was 1, when clearly I state there a diagnostic
When tested analyzer, went great
For the code fix provider, I don't really know how to take the code inside the else block and just remove the else keyword + braces

### CODE REVIEW

**Comment by mkrueger** [comment]
As usual: without the code fix provider it's not fully testable.

**Comment by Kavignon** [comment]
What do you mean by different syntax? The ElseClause was what the roslyn window gave me.
What's is currently wrong with what was written? 
The HasConflicingNames made me confuse. I did not understand what it did or how to port.  I forgot to ask you about it

**Comment by Kavignon** [comment]
@mkrueger ?

**Comment by mkrueger** [comment]
I mean that you're doing it again - use the child nodes for a situation where properties are for. And you simply take the first block - which is usually the one in the true branch.

**Comment by Kavignon** [comment]
There is no use of child nodes in the three files that I have modified in
this pull request. Could you please identify where you saw the use of child
nodes ? Thank you : -)

**Comment by Kavignon** [comment]
The block that I took is the block syntax of the else. I don't get what you
meant by your comment when you said  I simply take the first block. There's
only one block in the else and after checking if everything is in order, I
go around and analyze the block's flow to see if it's redundant or not.
The logic seemed fine to me. The only thing that was not working was that
when I used InsertBefore, the tests were telling me that the item specified
was not a member of the list. Which I did not really get...

**Comment by mkrueger** [comment]
I fixed that one.

**Comment by Kavignon** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Kevin

Confirm that you know Kevin: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=K0c0J8bJ&invitationId=6208290943678889985&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eivzc5n95%7Es2








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ivzc5n95-s2&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGuua4gnqWudAAAAVihH35NpezuvMV3GrZSK9RaRxkVmxdn7B_cXtwcERky3fFeeVRTJzY0YYeqtFjHo4PXj5oBJ_Nswex7dCPcP1pXGHkHgVKRT7W9I18Xa2KIOxRMQjEBu7StlFIqRvO76qSdJGKsmYihuLm7tmfL4r21_Yr6RRqP4DdgfB4txTeXcac4_JMCktZK-gzBZxfBSY1pZEY_Lg&eid=0-ivzc5n95-s2


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ivzc5n95-s2&a=customerServiceUrl&ek=invite_guest

© 2016 LinkedIn Corporation, 1000 West Maude Avenue, Sunnyvale, CA 94085. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Kavignon** [comment]
Kevin Avignon would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=K0c0J8bJ&invitationId=6208290943678889985&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-xh3ep0%7Eiw6ms98p%7E8x

View Kevin Avignon&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=K0c0J8bJ&invitationId=6208290943678889985&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-xh3ep0%7Eiw6ms98p%7E8x





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=xh3ep0-iw6ms98p-8x&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=xh3ep0-iw6ms98p-8x&loid=AQGJv1TO1uSa6AAAAVi8OBPUd5hWCyN3vRexsgIvQPDw0NhzIJgeFhQ3zRXy3hyoJ2SBdLXsQ_0wcxcJE7tmMiANb3oAXVmFYDVWnpIbjPls8qhW4HeZSjLAyJ-x2_u6tJyl4sp27L1qWTAPZFEffrBkHUNe-gTsEjqiVZd5Wg4mmJrYI8Mu7zZ_rpH-oJrTxOR5x2pliUIckE45Jc06kBx7Wv3Lsg

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=xh3ep0-iw6ms98p-8x&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request closed without merging**
