### PR TITLE
Mark analyser package as a development-only dependency.

### PR DESCRIPTION
**Pull request by tintoy**
Without this change, packages built from projects will include RefactoringEssentials as a dependency of their package.

### CODE REVIEW

**Comment by christophwille** [comment]
The nuspecs are generated from the .tt files

**Comment by tintoy** [comment]
Oops! Sorry, should have spotted that. Will fix that up.

**Comment by christophwille** [comment]
For our later reference: https://docs.nuget.org/Release-Notes/NuGet-2.7#development-only-dependencies

**Comment by Rpinski** [comment]
Thx!

**Pull request merged**
